import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
// import { ParallaxBackground } from "@/components/parallax";
// import { StarBackground } from "@/components/starbg";

const onest = localFont({
  src: "./fonts/Onest.ttf",
  variable: "--font-onest",
  weight: "100 200 300 400 500 600 700 800 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${onest.variable} antialiased`}>
        <div className="relative w-full h-screen">
          {/* <StarBackground />
          <ParallaxBackground /> */}
          {children}
        </div>
      </body>
    </html>
  );
}
